name: Deploy Pull Request to Ephemeral Railway Environment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Declare some variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
    
    - name: Another step
      run: |
        echo "Branch: ${{ env.branch }}"
        echo "Sha: ${{ env.sha_short }}"

    # - name: Set INITIAL_SHA as environment variable
    #   run: echo "INITIAL_SHA=$(cat initial_sha.txt)" >> $GITHUB_ENV

  #   - name: Generate dynamic variables
  #     id: generate-vars
  #     run: |
  #       # This is just a mock command. Replace with your actual command to generate variables.
  #       echo "DYNAMIC_VAR=value123" >> $GITHUB_ENV
  
  #   - name: Create PR environment on Railway
  #     if: github.event.action == 'opened'
  #     uses: Faolain/railway-pr-deploy@v1.0.5
  #     with:
  #       RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #       PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  #       SRC_ENVIRONMENT_NAME: production
  #       DEST_ENV_NAME: pr-${{ github.event.pull_request.number }}-${{ env.INITIAL_SHA }}
  #       PROVIDER: python
  #       ENV_VARS: '{"database_url": "${{ env.DYNAMIC_VAR }}", "other_key": "other_value"}'
  #       branch_name: ${{ github.head_ref }}
  #       repository: ${{ github.repository }}
  # cleanup:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download SHA artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: initial-sha
        
  #   - name: Set INITIAL_SHA as environment variable
  #     run: echo "INITIAL_SHA=$(cat initial_sha.txt)" >> $GITHUB_ENV

  #   - name: Delete PR environment on Railway
  #     uses: Faolain/railway-pr-delete@v1.0.0
  #     with:
  #       RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #       PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  #       DEST_ENV_NAME: pr-${{ github.event.pull_request.number }}-${{  env.INITIAL_SHA }}